import os



Import('env')
myenv=env.Clone()

files="test.cpp"

cpppath='''
	../include
	'''

LIBPATH='''
	../lib
	'''
	
LIBS='''
	ehp
	'''
myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 -Wall -Werror -fmax-errors=1 -g ")

lib=myenv.Program("test.exe",  Split(files), LIBPATH=Split(LIBPATH), LIBS=Split(LIBS))
install=myenv.Install("../lib/", lib)
Default(install)

Return('install')
