#   Copyright 2017-2018 University of Virginia
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os



Import('env')
myenv=env.Clone()

files="ehp.cpp"

cpppath='''
	../include
	'''
cpppath=cpppath+Dir('.').srcnode().abspath+'/../third-party/elfio-code'

AddOption('--no_elfio',
          dest='no_elfio',
          action='store_true',
          default=False,
          help='Do not use Elfio library to parse elf files')

cpp_defines={}
if( not GetOption('no_elfio')):
    cpp_defines['USE_ELFIO']=1

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("")

myenv=myenv.Clone(CPPPATH=Split(cpppath),CPPDEFINES=cpp_defines)
myenv.Append(CXXFLAGS = " -std=c++11 -Wall -Werror -fmax-errors=2 -fPIC ")

lib1=myenv.Library("ehp",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install1=myenv.Install("../lib/", lib1)
Default(install1)

lib2=myenv.SharedLibrary("ehp",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install2=myenv.Install("../lib/", lib2)
Default(install2)

install=install1+install2

Return('install')
