import os



Import('env')
myenv=env.Clone()

files="ehp.cpp"

cpppath='''
	../include
	../third-party/elfio-code
        '''


LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 -Wall -Werror -fmax-errors=2")

lib=myenv.Library("ehp",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("../lib/", lib)
Default(install)

Return('install')
